set_targetdir("./")
set_languages("cxx17")

set_toolchains("clang")
set_warnings("allextra", "error")
set_optimize("fastest")
set_symbols("debug")

add_requires("glfw")
add_requires("glad")
add_requires("stb")
add_requires("imgui", {configs = {glfw = true, opengl3 = true}})

namespace("GlbParser")
includes("submodules/GlbParser")
namespace_end()

target("scop")
    set_kind("binary")
    add_files("srcs/**.cpp")
    add_includedirs("srcs")
    add_packages("glfw")
    add_packages("glad")
    add_packages("stb")
    add_packages("imgui")
    add_deps("GlbParser::GlbParser")