set_targetdir("./")
set_languages("cxx17")

set_toolchains("clang")
add_ldflags("-stdlib=libc++")
add_cxxflags("-std=c++17")
add_cxxflags("-Wall")
add_cxxflags("-Werror")
add_cxxflags("-Wextra")
add_cxxflags("-O3")
add_cxxflags("-g")

add_requires("glfw")
add_requires("glad")
add_requires("stb")
add_requires("glm")
add_requires("imgui", {configs = {glfw = true, opengl3 = true}})
includes("submodules/Toolbox")
includes("submodules/Matrix")
includes("submodules/GlbParser")

target("scop")
    set_kind("binary")
    add_files("srcs/**.cpp")
    add_includedirs("srcs")
    add_packages("glfw")
    add_packages("glad")
    add_packages("stb")
    add_packages("glm")
    add_packages("imgui")
    add_deps("Toolbox")
    add_deps("Matrix")
    add_deps("GlbParser")
    add_includedirs("GlbParser/srcs")